name: ci

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Set up binary cache
        uses: cachix/cachix-action@v16
        with:
          name: abiopetaja
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Run checks
        run: nix flake check -L --system x86_64-linux

